### ISSUE TITLE
Error result, affer NUM_CLASS be changed

### ISSUE THREAD

**Issue by ouyangpingbu** [Carnon/trt_yolov7#3]
你好，当 NUM_CLASS 改变时，decode.cu等需要做哪些修改？

**Comment by Carnon** [comment]
更新tiny分支的代码， 或者修改 63 和67行      

85  = NUM_CLASS+5

**Comment by gy-zkj** [comment]
> 

改了63和67 检测出来的也是有问题  比较乱 还需要改哪里吗 我再看了看 感觉修改类别好像就只有decode.cu里边了，
麻烦大佬再帮忙看看，能成功转出engine

**Comment by ouyangpingbu** [comment]
> 



> > 
> 
> 改了63和67 检测出来的也是有问题 比较乱 还需要改哪里吗 我再看了看 感觉修改类别好像就只有decode.cu里边了， 麻烦大佬再帮忙看看，能成功转出engine

**Comment by ouyangpingbu** [comment]
> > 
> 
> 改了63和67 检测出来的也是有问题 比较乱 还需要改哪里吗 我再看了看 感觉修改类别好像就只有decode.cu里边了， 麻烦大佬再帮忙看看，能成功转出engine

可能训练时最后一层是 IDetect层， 这里是Detect层
